 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: avijitsaha2997/gitartwork@v1
         with:
            # Use this username's contribution graph 
            user_name: avijitsaha2997
            # Text on contribution graph 
            text: AVIJIT
       - uses: avijitsaha2997/simple-push-action@v1
